server:
  port: 9020

spring:
  application:
    name: LEAVESERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/leavemanagement
    username: postgres
    password: postgres

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka