spring:
  application:
    name: LOAN-SERVICE
  
  datasource:
    driver-class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/loanmgmt
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true