spring:
  application:
    name: SPRING-SECURITY

  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: postgres

  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    view:
      prefix: /jsps/
      suffix: .jsp

logging:
  level:
    org:
      springframework:
        security: DEBUG